/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PropuestasRouteImport } from './routes/propuestas'
import { Route as IntegrantesRouteImport } from './routes/integrantes'
import { Route as IndexRouteImport } from './routes/index'

const PropuestasRoute = PropuestasRouteImport.update({
  id: '/propuestas',
  path: '/propuestas',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrantesRoute = IntegrantesRouteImport.update({
  id: '/integrantes',
  path: '/integrantes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/integrantes': typeof IntegrantesRoute
  '/propuestas': typeof PropuestasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/integrantes': typeof IntegrantesRoute
  '/propuestas': typeof PropuestasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/integrantes': typeof IntegrantesRoute
  '/propuestas': typeof PropuestasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/integrantes' | '/propuestas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/integrantes' | '/propuestas'
  id: '__root__' | '/' | '/integrantes' | '/propuestas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntegrantesRoute: typeof IntegrantesRoute
  PropuestasRoute: typeof PropuestasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/propuestas': {
      id: '/propuestas'
      path: '/propuestas'
      fullPath: '/propuestas'
      preLoaderRoute: typeof PropuestasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrantes': {
      id: '/integrantes'
      path: '/integrantes'
      fullPath: '/integrantes'
      preLoaderRoute: typeof IntegrantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntegrantesRoute: IntegrantesRoute,
  PropuestasRoute: PropuestasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
